version: "3.2"
services:
  db:
    image: postgres:latest
    restart: always
    container_name: aoe_a
    ports:
      - "5432:5432"
    networks:
      - postgresql
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "aoe-db"
    volumes:
      - ./data:/var/lib/postgresql/data

  scrapper-aoe:
    build: ./app
    container_name: aoeScrapper_C
    links: 
      - db
    networks:
      - postgresql
    volumes:
      - type: bind
        source: ./app
    command: ["python", "./scrapper.py"]
    depends_on:
     - db
